delete from dbo.ACCION_BITACORA;
delete from dbo.ACCION_COBRANZA;
delete from dbo.AJUSTE_BODEGA;
delete from dbo.AJUSTE_DESPACHAR_NOTA_VENTA;
delete from dbo.AJUSTE_FACTURAR_NOTA_VENTA;
delete from dbo.AJUSTE_PAGO_NOTA_VENTA;
delete from dbo.ALERTA;
delete from dbo.ALERTA_USUARIO;
delete from dbo.ARRIENDO;
delete from dbo.ASIG_NRO_DOC_SII;
delete from dbo.ATRIBUTO_PRODUCTO;
delete from dbo.ATRIBUTO_PRODUCTO_4D;
delete from dbo.AUTORIZA_MENU;
delete from dbo.AUTORIZA_TE;
delete from dbo.AUX_ASIG_PAGO_FACT
delete from dbo.AUX_ASIG_PAGO_NV
delete from dbo.AUX_DOCUMENTO
delete from dbo.AUX_FACTURA
delete from dbo.AUX_GUIA_DESPACHO
delete from dbo.AUX_INGRESO_PAGO
delete from AUX_ITEM_FACTURA
delete from dbo.AUX_ITEM_GUIA_DESPACHO
delete from dbo.AUX_ITEM_NOTA_CREDITO
delete from dbo.AUX_ITEM_NOTA_VENTA
delete from dbo.AUX_ITEM_ORDEN_COMPRA
delete from dbo.AUX_NOTA_CREDITO
delete from dbo.AUX_NOTA_VENTA
delete from dbo.aux_nv_sin_oc_pagadas
delete from dbo.AUX_ORDEN_COMPRA
delete from dbo.aux_precio_prod
delete from dbo.BITACORA_COTIZACION
delete from dbo.BITACORA_EMPRESA
delete from dbo.BITACORA_FACTURA
delete from dbo.BODEGA 
delete from dbo.CARGO 
delete from dbo.CENTRO_COSTO 
delete from CENTRO_COSTO_EMPRESA
delete from dbo.CHEQUE_RENTA
delete from dbo.CHEQUE_TODOINOX
delete from dbo.CIERRE_BODEGA
delete from dbo.CONTACTO 
delete from dbo.CONTACTO_PERSONA 
delete from dbo.CONTACTO_PERSONA_TELEFONO
delete from dbo.CONTACTO_TELEFONO
delete from dbo.COSTO_PRODUCTO
delete from dbo.COTIZACION 
delete from dbo.COTIZACION_ARRIENDO
delete from dbo.CUENTA_COMPRA 
delete from dbo.CUENTA_CONTABLE 
delete from dbo.CUENTA_CORRIENTE 
delete from dbo.DEPOSITO
delete from dbo.DESARROLLADOR_SW 
delete from dbo.DESTINATARIO 
delete from dbo.DESTINATARIO_WEB
delete from dbo.DETALLE_CAMBIO
delete from dbo.DETALLE_CAMBIO_RELACIONADA
delete from dbo.DOC_INGRESO_PAGO 
delete from dbo.DOC_NOTA_VENTA
delete from dbo.DOMINIO
delete from dbo.DSCTO_CORPORATIVO_EMPRESA
delete from dbo.EMPRESA 
delete from dbo.EMPRESA_CUENTA_CORRIENTE
delete from dbo.ENTRADA_BODEGA 
delete from dbo.ENVIO_EMPRESA
delete from dbo.ENVIO_FACTURA
delete from dbo.ENVIO_FAPROV
delete from dbo.ENVIO_NCPROV
delete from dbo.ENVIO_NOTA_CREDITO
delete from dbo.ENVIO_SOFTLAND
delete from dbo.ESTADO_AJUSTE_BODEGA
delete from dbo.ESTADO_ARRIENDO
delete from dbo.ESTADO_DEPOSITO
delete from dbo.ESTADO_ENVIO
delete from dbo.ESTADO_MOD_ARRIENDO
delete from dbo.ESTADO_ORDEN_COMPRA
delete from dbo.ESTADO_SOLUCION_SW 
delete from dbo.EXECUTE_SP
delete from dbo.FACTURA 
delete from dbo.FACTURA_EXPORTACION
delete from dbo.FAMILIA
delete from dbo.FAMILIA_ACCESORIO
delete from dbo.FAMILIA_PRODUCTO 
delete from dbo.FAPROV 
delete from dbo.GRUPO
delete from dbo.GRUPO_USUARIO
delete from GUIA_DESPACHO 
delete from GUIA_DESPACHO_FACTURA
delete from dbo.GUIA_RECEPCION 
delete from dbo.IMAGEN_ERROR_SW
delete from dbo.IMPRESORA_DTE
delete from dbo.INF_GD_POR_FACTURAR
delete from dbo.INF_RESULTADO
delete from dbo.INF_VENTAS_POR_EQUIPO
delete from dbo.INF_VENTAS_POR_MES
delete from dbo.INGRESO_PAGO 
delete from dbo.INGRESO_PAGO_FACTURA 
delete from dbo.ITEM_AJUSTE_BODEGA
delete from dbo.ITEM_ARRIENDO
delete from dbo.ITEM_COTIZACION 
delete from dbo.ITEM_DEPOSITO
delete from dbo.ITEM_ENTRADA_BODEGA
delete from dbo.ITEM_FACTURA
delete from dbo.ITEM_FAPROV
delete from dbo.ITEM_GUIA_DESPACHO
delete from dbo.ITEM_GUIA_RECEPCION
delete from dbo.ITEM_MOD_ARRIENDO
delete from dbo.ITEM_NOTA_CREDITO
delete from dbo.ITEM_NOTA_DEBITO
delete from dbo.ITEM_NOTA_VENTA 
delete from dbo.ITEM_NOTA_VENTA_ELIMINADA
delete from dbo.ITEM_ORDEN_COMPRA
delete from dbo.ITEM_SALIDA_BODEGA
delete from dbo.ITEM_SOLICITUD_COTIZACION
delete from dbo.ITEM_TRASPASO_BODEGA
delete from dbo.LLAMADO 
delete from dbo.LLAMADO_ACCION 
delete from dbo.LLAMADO_CONVERSA
delete from dbo.LLAMADO_DESTINATARIO
delete from dbo.LOCK_TABLE
delete from dbo.LOG_AUDITORIA
delete from dbo.LOG_CAMBIO
delete from dbo.MANTENCION_SW
delete from dbo.MARCA
delete from dbo.MOD_ARRIENDO
delete from dbo.MODIFICA_PRECIO_COTIZACION
delete from dbo.MODIFICA_PRECIO_NOTA_VENTA
delete from dbo.MODIFICA_PRECIO_ORDEN_COMPRA
delete from dbo.MONEDA
delete from dbo.MONTO_DOC_ASIGNADO
delete from dbo.NCPROV 
delete from dbo.NCPROV_FAPROV
delete from dbo.NOTA_CREDITO
delete from dbo.NCPROV
delete from dbo.NCPROV_FAPROV
delete from dbo.NOTA_CREDITO
delete from dbo.NOTA_DEBITO
delete from dbo.NOTA_VENTA 
delete from dbo.NOTA_VENTA_DOCS
delete from dbo.numerica
delete from dbo.ORDEN_COMPRA
delete from dbo.ORDEN_PAGO 
delete from dbo.PAGO_FAPROV 
delete from dbo.PAGO_FAPROV_FAPROV
delete from dbo.PARAMETRO_PORC
delete from dbo.PARTICIPACION 
delete from dbo.PARTICIPACION_ORDEN_PAGO
delete from dbo.PERFIL 
delete from dbo.PERSONA 
delete from dbo.PRE_ORDEN_COMPRA 
delete from dbo.PRODUCTO 
delete from dbo.PRODUCTO_4D
delete from dbo.PRODUCTO_COMPUESTO
delete from dbo.PRODUCTO_LOCAL
delete from dbo.PRODUCTO_PROVEEDOR
delete from dbo.PRORROGA
delete from dbo.PROTESTO
delete from dbo.SALIDA_BODEGA
delete from dbo.SISTEMA
delete from dbo.SOLICITUD_COTIZACION 
delete from dbo.SOLUCION_SW
delete from dbo.SUCURSAL 
delete from dbo.TRASPASO_BODEGA
delete from dbo.VALOR_DEFECTO_COMPRA
delete from dbo.VENDEDOR_SOFLAND
delete from dbo.X_DTE_151211
delete from dbo.XCECO
delete from dbo.XITEM_CONTRATO
delete from dbo.ZONA 
delete from dbo.USUARIO 
delete from dbo.ZONA_FAMILIA




