alter PROCEDURE [dbo].[spi_anexo_arriendo](@ve_cod_arriendo	NUMERIC)
AS
BEGIN
	DECLARE @TEMPO TABLE  
        (ITEM								NUMERIC
        ,ST_COD_PRODUCTO					VARCHAR(30)
		,ST_NOM_PRODUCTO					VARCHAR(100)
		,ST_CANTIDAD						NUMERIC(10,2)
		,NOM_EMPRESA						VARCHAR(100)
		,RUT								NUMERIC
		,DIG_VERIF							VARCHAR(1)
		,DIRECCION							VARCHAR(100)
		,NOM_COMUNA							VARCHAR(100)
		,NOM_CIUDAD							VARCHAR(100)
		,NOM_PAIS							VARCHAR(100)
		,REFERENCIA							VARCHAR(100)
		,CENTRO_COSTO_CLIENTE				VARCHAR(100)
		,NOM_ARRIENDO						VARCHAR(100)
		,UBICACION_CONTRATO					VARCHAR(300)
		,EJECUTIVO_CONTRATO					VARCHAR(300)
		,USUARIO							VARCHAR(100)
		,VISIBLE_FECHA						VARCHAR(1)
		,FECHA_GUIA_DESPACHO				VARCHAR(100))
		
	DECLARE
		 @ITEM								NUMERIC	
        ,@ST_COD_PRODUCTO					VARCHAR(30)
		,@ST_NOM_PRODUCTO					VARCHAR(100)
		,@ST_CANTIDAD						NUMERIC(10,2)
		,@NOM_EMPRESA						VARCHAR(100)
		,@RUT								NUMERIC
		,@DIG_VERIF							VARCHAR(1)
		,@DIRECCION							VARCHAR(100)
		,@NOM_COMUNA						VARCHAR(100)
		,@NOM_CIUDAD						VARCHAR(100)
		,@NOM_PAIS							VARCHAR(100)
		,@REFERENCIA						VARCHAR(100)
		,@CENTRO_COSTO_CLIENTE				VARCHAR(100)
		,@NOM_ARRIENDO						VARCHAR(100)
		,@UBICACION_CONTRATO				VARCHAR(300)
		,@EJECUTIVO_CONTRATO				VARCHAR(300)
		,@USUARIO							VARCHAR(100)
		,@COD_ESTADO_ARRIENDO				NUMERIC
		,@VISIBLE_FECHA						VARCHAR(1)
		,@FECHA_GUIA_DESPACHO				VARCHAR(100)
		
	
	SELECT @COD_ESTADO_ARRIENDO = COD_ESTADO_ARRIENDO
	FROM ARRIENDO
	WHERE COD_ARRIENDO = @ve_cod_arriendo
	
	SELECT top 1 @FECHA_GUIA_DESPACHO = CONVERT(VARCHAR, G.FECHA_GUIA_DESPACHO, 103)
	FROM GUIA_DESPACHO G, MOD_ARRIENDO M
	WHERE G.COD_TIPO_GUIA_DESPACHO =  5
	AND G.COD_ESTADO_DOC_SII IN (2, 3)
	AND M.COD_MOD_ARRIENDO = G.COD_DOC
	AND M.COD_ARRIENDO = @ve_cod_arriendo
	ORDER BY G.FECHA_GUIA_DESPACHO ASC
	
	if(@FECHA_GUIA_DESPACHO IS NOT NULL AND @COD_ESTADO_ARRIENDO = 2)
		set @VISIBLE_FECHA = 'S'	
	else
		set @VISIBLE_FECHA = 'N'
		
	DECLARE C_ANEXO CURSOR FOR 
	SELECT DISTINCT I.COD_PRODUCTO ST_COD_PRODUCTO
								,I.NOM_PRODUCTO ST_NOM_PRODUCTO
								,dbo.f_bodega_stock(I.COD_PRODUCTO, A.COD_BODEGA, getdate()) ST_CANTIDAD
								,E.NOM_EMPRESA
								,E.RUT
								,E.DIG_VERIF
								,SU.DIRECCION
								,CO.NOM_COMUNA
								,CI.NOM_CIUDAD
								,PA.NOM_PAIS
								,A.REFERENCIA
								,A.CENTRO_COSTO_CLIENTE
								,A.NOM_ARRIENDO
								,(A.UBICACION_DIRECCION +' - '+ A.UBICACION_COMUNA + ' - ' +A.UBICACION_CIUDAD)	UBICACION_CONTRATO
								,(A.EJECUTIVO_CONTACTO +' - '+ A.EJECUTIVO_TELEFONO + ' - ' +A.EJECUTIVO_MAIL)	EJECUTIVO_CONTRATO
								,U.NOM_USUARIO USUARIO
				FROM 			ITEM_MOD_ARRIENDO I
					 			,MOD_ARRIENDO M
					 			,ARRIENDO A
					 			,PERSONA P
					 			,USUARIO U
					 			,EMPRESA E
					 			,SUCURSAL SU LEFT OUTER JOIN COMUNA CO ON SU.COD_COMUNA = CO.COD_COMUNA
                                  			 LEFT OUTER JOIN CIUDAD CI ON SU.COD_CIUDAD = CI.COD_CIUDAD
                                  			 LEFT OUTER JOIN PAIS PA ON SU.COD_PAIS = PA.COD_PAIS
				WHERE M.COD_ARRIENDO = @ve_cod_arriendo
				  AND I.COD_MOD_ARRIENDO = M.COD_MOD_ARRIENDO
				  AND A.COD_ARRIENDO = M.COD_ARRIENDO
				  AND SU.COD_SUCURSAL = A.COD_SUCURSAL
				  AND P.COD_PERSONA = A.COD_PERSONA
				  AND U.COD_USUARIO = A.COD_USUARIO
				  AND E.COD_EMPRESA = A.COD_EMPRESA
				  AND DBO.F_BODEGA_STOCK(I.COD_PRODUCTO, A.COD_BODEGA, GETDATE()) > 0
	
	SET @ITEM = 0			  
	OPEN C_ANEXO
	FETCH C_ANEXO INTO @ST_COD_PRODUCTO, @ST_NOM_PRODUCTO, @ST_CANTIDAD, @NOM_EMPRESA, @RUT
						, @DIG_VERIF, @DIRECCION, @NOM_COMUNA, @NOM_CIUDAD, @NOM_PAIS, @REFERENCIA
						, @CENTRO_COSTO_CLIENTE, @NOM_ARRIENDO, @UBICACION_CONTRATO, @EJECUTIVO_CONTRATO
						, @USUARIO
	WHILE @@FETCH_STATUS = 0 BEGIN
	SET @ITEM = @ITEM + 1
	
	INSERT INTO @TEMPO (ITEM,					ST_COD_PRODUCTO,	ST_NOM_PRODUCTO,	ST_CANTIDAD,
						NOM_EMPRESA,			RUT,				DIG_VERIF,			DIRECCION,
						NOM_COMUNA,				NOM_CIUDAD,			NOM_PAIS,			REFERENCIA,
						CENTRO_COSTO_CLIENTE,	NOM_ARRIENDO,		UBICACION_CONTRATO,	EJECUTIVO_CONTRATO,
						USUARIO,				VISIBLE_FECHA,		FECHA_GUIA_DESPACHO)
	VALUES	(@ITEM,					@ST_COD_PRODUCTO,	@ST_NOM_PRODUCTO,	@ST_CANTIDAD,
			 @NOM_EMPRESA,			@RUT,				@DIG_VERIF,			@DIRECCION,
			 @NOM_COMUNA,			@NOM_CIUDAD,		@NOM_PAIS,			@REFERENCIA,
			 @CENTRO_COSTO_CLIENTE,	@NOM_ARRIENDO,		@UBICACION_CONTRATO,@EJECUTIVO_CONTRATO,
			 @USUARIO,				@VISIBLE_FECHA,		@FECHA_GUIA_DESPACHO)												  
	
		FETCH C_ANEXO INTO @ST_COD_PRODUCTO, @ST_NOM_PRODUCTO, @ST_CANTIDAD, @NOM_EMPRESA, @RUT
						, @DIG_VERIF, @DIRECCION, @NOM_COMUNA, @NOM_CIUDAD, @NOM_PAIS, @REFERENCIA
						, @CENTRO_COSTO_CLIENTE, @NOM_ARRIENDO, @UBICACION_CONTRATO, @EJECUTIVO_CONTRATO
						, @USUARIO
	END
	CLOSE C_ANEXO
	DEALLOCATE C_ANEXO
	
	SELECT * FROM @TEMPO	
END